# Generated by Django 5.2.15 on 2026-07-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnhancementJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('original', models.ImageField(upload_to='uploads/originals/')),
                ('enhanced', models.ImageField(blank=True, upload_to='uploads/enhanced/')),
                ('mode', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Enhanced'), ('batch', 'Batch')], default='ai', max_length=20)),
                ('brightness', models.FloatField(default=1.0)),
                ('contrast', models.FloatField(default=1.0)),
                ('sharpness', models.FloatField(default=1.0)),
                ('saturation', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
