# Generated by Django 5.2.15 on 2026-07-05 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0003_allow_null_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhancementjob',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI Enhanced'), ('batch', 'Batch'), ('background', 'Background Removal')], default='ai', max_length=20),
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
            },
        ),
    ]
