# Generated by Django 5.2.15 on 2026-07-06 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0004_add_usercredit'),
        ('enhancer', '0004_alter_enhancementjob_mode_usercredit'),
    ]

    operations = [
    ]
