# Generated by Django 5.2.15 on 2026-07-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enhancer', '0006_anonymous_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouscredit',
            options={'verbose_name': 'Anonymous Credit', 'verbose_name_plural': 'Anonymous Credits'},
        ),
    ]
